# Generated by Django 5.1 on 2024-08-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafioadl", "0002_alter_subtarea_description_alter_tarea_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtarea",
            name="tarea_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtarea",
                to="desafioadl.tarea",
            ),
        ),
    ]
